version: '3.4'

services:
  catalogdb:
    image: mongo:4.2-bionic

  basketdb:
    image: redis:6.2.1-alpine

  discountdb:
#    image: postgres:13-alpine
    image: timescale/timescaledb:2.2.0-pg13

  orderdb:
    image: mcr.microsoft.com/azure-sql-edge

  rabbitmq:
    image: rabbitmq:3-management-alpine

  portainer:
    image: portainer/portainer-ce:2.1.1-alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data: