version: '3.4'

services:
  catalogdb:
    image: mongo:4.2-bionic
  
  basketdb:
    image: redis:6.2.1-alpine
  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
      
volumes:
  mongo_data: